name: Build and deploy to IBM Cloud Foundry

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  IBM_CLOUD_REGION: eu-gb
  IBM_CLOUD_GROUP: Default
  IBM_CLOUD_SPACE: dealershipC11
  IBM_CLOUD_ORG: romana.leitgeb247@gmail.com
  MANIFEST_NAME: manifest.yml
  IBM_CLOUD_API: ${{secrets.IBM_CLOUD_API_KEY}}
  CI: false

defaults:
  run:
    working-directory: server

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build client
        run: |
          npm install
          npm run-script build
        working-directory: server/frontend
      - name: build server
        run: |
          npm install
        working-directory: server/backend
      - name: Install IBM CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
        shell: bash
      - name: Install CF plugin
        run: ibmcloud cf install -f
        shell: bash
      - name: Log into IBM Cloud
        run: |
          ibmcloud login --apikey "$IBM_CLOUD_API" -r "$IBM_CLOUD_REGION" -g "$IBM_CLOUD_GROUP"
        shell: bash
      - name: Target CF
        run: ibmcloud target --cf-api https://api.$IBM_CLOUD_REGION.cf.cloud.ibm.com -r $IBM_CLOUD_REGION -o $IBM_CLOUD_ORG -s $IBM_CLOUD_SPACE
        shell: bash
      - name: List all applications
        run: ibmcloud cf apps
        shell: bash
      - name: Deploy manifest file
        run: ibmcloud cf push -f ./$MANIFEST_NAME
        shell: bash
        working-directory: server/backend
